FROM python:3.13-rc-slim

WORKDIR /root/api

COPY requirements.txt requirements.txt
RUN pip3 install --upgrade pip

RUN pip3 install -r requirements.txt

EXPOSE 5000

COPY . .

CMD [ "python3", "main.py"]